# SPDX-FileCopyrightText: (C) 2025 pierventre
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = [
  "VERSION",
  "**.md",
  "data/**",
]

precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2025 pierventre"
SPDX-License-Identifier = "MIT"